import { createHash, randomBytes, scrypt as scryptCallback, timingSafeEqual } from "node:crypto";
import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { Pool, type PoolClient } from "pg";
import { createInitialReviewState, recordReviewOutcome, type ReviewItemIdentity, type ReviewItemState, type ReviewRating } from "../core/review-scheduler";

const scrypt=(password:string,salt:Buffer,length:number,options:{N:number;r:number;p:number})=>new Promise<Buffer>((resolve,reject)=>scryptCallback(password,salt,length,options,(error,derived)=>error?reject(error):resolve(derived)));
const migrationLock = 0x57534d;
export interface DatabaseConfig { readonly url:string; readonly poolMax:number; readonly connectionTimeoutMs:number; readonly queryTimeoutMs:number }
export interface AuthenticatedUser { readonly id:string; readonly username:string; readonly role:"admin"|"user" }
export interface DatabaseSession extends AuthenticatedUser { readonly sessionId:string; readonly csrfTokenHash:string }
export function databaseConfig(env:NodeJS.ProcessEnv=process.env):DatabaseConfig|undefined{const url=env.DATABASE_URL?.trim();return url?{url,poolMax:10,connectionTimeoutMs:5000,queryTimeoutMs:10000}:undefined}
export function createDatabasePool(c:DatabaseConfig){return new Pool({connectionString:c.url,max:c.poolMax,connectionTimeoutMillis:c.connectionTimeoutMs,idleTimeoutMillis:30000,query_timeout:c.queryTimeoutMs,application_name:"whacksmacker"})}
export async function assertDatabaseReady(pool:Pool,attempts=5){let last:unknown;for(let i=0;i<attempts;i++){try{await pool.query("SELECT 1");return}catch(e){last=e;await new Promise(r=>setTimeout(r,Math.min(250*2**i,2000)))}}throw new Error("PostgreSQL unavailable after "+attempts+" attempts: "+redactDatabaseError(last))}
export function redactDatabaseError(e:unknown){return(e instanceof Error?e.message:String(e)).replace(/postgres(?:ql)?:\/\/[^\s@]+@/giu,"postgresql://[redacted]@")}
export function installedMigrationDirectory(){return join(__dirname,"../../../migrations")}
export async function migrateDatabase(pool:Pool,dir=join(process.cwd(),"migrations")){const c=await pool.connect();try{await c.query("SELECT pg_advisory_lock($1)",[migrationLock]);await c.query("CREATE TABLE IF NOT EXISTS schema_migrations(version text PRIMARY KEY,applied_at timestamptz NOT NULL DEFAULT now())");const applied=new Set((await c.query<{version:string}>("SELECT version FROM schema_migrations")).rows.map(x=>x.version));const done:string[]=[];for(const f of(await readdir(dir)).filter(x=>/^\d+_.+\.sql$/u.test(x)).sort()){if(applied.has(f))continue;await c.query("BEGIN");try{await c.query(await readFile(join(dir,f),"utf8"));await c.query("INSERT INTO schema_migrations(version) VALUES($1)",[f]);await c.query("COMMIT");done.push(f)}catch(e){await c.query("ROLLBACK");throw e}}return done}finally{await c.query("SELECT pg_advisory_unlock($1)",[migrationLock]).catch(()=>undefined);c.release()}}
export async function databaseMigrationStatus(pool:Pool,dir=join(process.cwd(),"migrations")){await pool.query("CREATE TABLE IF NOT EXISTS schema_migrations(version text PRIMARY KEY,applied_at timestamptz NOT NULL DEFAULT now())");const known=(await readdir(dir)).filter(x=>/^\d+_.+\.sql$/u.test(x)).sort(),applied=new Set((await pool.query<{version:string}>("SELECT version FROM schema_migrations")).rows.map(x=>x.version));return known.map(version=>({version,applied:applied.has(version)}))}
export function normalizeUsername(value:string){const d=value.normalize("NFKC").trim();if(!d||d.length>64||/[\p{Cc}\p{Cf}]/u.test(d)||!/^[\p{L}\p{N}_.@+-]+$/u.test(d))throw new Error("Username must be 1-64 safe letters, numbers, or . _ @ + - characters.");return d.toLocaleLowerCase("en-US")}
export async function hashPassword(password:string){if(password.length<12||password.length>1024)throw new Error("Password must be between 12 and 1024 characters.");const salt=randomBytes(16),N=16384,r=8,p=1,l=32,d=await scrypt(password,salt,l,{N,r,p}) as Buffer;return "wsm-scrypt-v1$N="+N+",r="+r+",p="+p+",l="+l+"$"+salt.toString("base64url")+"$"+d.toString("base64url")}
export async function verifyPassword(password:string,encoded:string){const m=encoded.match(/^wsm-scrypt-v1\$N=(\d+),r=(\d+),p=(\d+),l=(\d+)\$([^$]+)\$([^$]+)$/u);if(!m)return false;const e=Buffer.from(m[6],"base64url"),a=await scrypt(password,Buffer.from(m[5],"base64url"),Number(m[4]),{N:Number(m[1]),r:Number(m[2]),p:Number(m[3])}) as Buffer;return a.length===e.length&&timingSafeEqual(a,e)}
export async function createUser(pool:Pool,username:string,password:string,role:"admin"|"user"="user"){const display=username.normalize("NFKC").trim(),normalized=normalizeUsername(username),hash=await hashPassword(password);const q=await pool.query<{id:string;display_username:string;role:"admin"|"user"}>("INSERT INTO users(display_username,normalized_username,password_hash,role) VALUES($1,$2,$3,$4) RETURNING id,display_username,role",[display,normalized,hash,role]);await pool.query("INSERT INTO user_settings(user_id) VALUES($1)",[q.rows[0].id]);return{id:q.rows[0].id,username:q.rows[0].display_username,role:q.rows[0].role}}
export async function authenticateUser(pool:Pool,username:string,password:string){let n:string;try{n=normalizeUsername(username)}catch{return undefined}const q=await pool.query<any>("SELECT id,display_username,role,password_hash,enabled FROM users WHERE normalized_username=$1",[n]),u=q.rows[0];if(!u||!u.enabled||!await verifyPassword(password,u.password_hash))return undefined;await pool.query("UPDATE users SET last_login_at=now(),updated_at=now() WHERE id=$1",[u.id]);return{id:u.id,username:u.display_username,role:u.role} as AuthenticatedUser}
const hashToken=(v:string)=>createHash("sha256").update(v).digest("hex");
export async function createSession(pool:Pool,user:AuthenticatedUser,ttl:number,address?:string,agent?:string){const token=randomBytes(32).toString("base64url"),csrf=randomBytes(24).toString("base64url");await pool.query("INSERT INTO sessions(user_id,token_hash,csrf_token_hash,expires_at,client_address,user_agent) VALUES($1,$2,$3,now()+$4*interval '1 second',$5,$6)",[user.id,hashToken(token),hashToken(csrf),ttl,address?.slice(0,128),agent?.slice(0,512)]);return{token,csrf}}
export async function resolveSession(pool:Pool,token:string){const q=await pool.query<any>("SELECT s.id session_id,u.id,u.display_username,u.role,s.csrf_token_hash FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>now() AND u.enabled=true",[hashToken(token)]),r=q.rows[0];if(!r)return undefined;await pool.query("UPDATE sessions SET last_seen_at=now() WHERE id=$1",[r.session_id]);return{sessionId:r.session_id,id:r.id,username:r.display_username,role:r.role,csrfTokenHash:r.csrf_token_hash} as DatabaseSession}
export async function revokeSession(pool:Pool,token:string){await pool.query("UPDATE sessions SET revoked_at=now() WHERE token_hash=$1 AND revoked_at IS NULL",[hashToken(token)])}
export async function revokeUserSessions(pool:Pool,userId:string){await pool.query("UPDATE sessions SET revoked_at=now() WHERE user_id=$1 AND revoked_at IS NULL",[userId])}
export function csrfMatches(raw:string,stored:string){const a=Buffer.from(hashToken(raw)),b=Buffer.from(stored);return a.length===b.length&&timingSafeEqual(a,b)}
export async function userSettings(pool:Pool,userId:string){const q=await pool.query<any>("SELECT source_locale,theme FROM user_settings WHERE user_id=$1",[userId]);return{locale:q.rows[0]?.source_locale??"zh-Hant-TW",theme:q.rows[0]?.theme??"light"}}
export async function updateUserSettings(pool:Pool,userId:string,locale:string,theme?:string){await pool.query("INSERT INTO user_settings(user_id,source_locale,theme) VALUES($1,$2,COALESCE($3,'light')) ON CONFLICT(user_id) DO UPDATE SET source_locale=EXCLUDED.source_locale,theme=COALESCE($3,user_settings.theme),updated_at=now()",[userId,locale,theme])}
export async function selectedPackages(pool:Pool,userId:string){return(await pool.query<{package_id:string;package_version:string}>("SELECT package_id,package_version FROM user_packages WHERE user_id=$1 AND enabled=true ORDER BY package_id",[userId])).rows}
export async function selectPackage(pool:Pool,userId:string,id:string,version:string){await pool.query("INSERT INTO user_packages(user_id,package_id,package_version,enabled) VALUES($1,$2,$3,true) ON CONFLICT(user_id,package_id,package_version) DO UPDATE SET enabled=true,updated_at=now()",[userId,id,version])}
export async function unselectPackage(pool:Pool,userId:string,id:string,version:string,drop:boolean){const c=await pool.connect();try{await c.query("BEGIN");await c.query("DELETE FROM user_packages WHERE user_id=$1 AND package_id=$2 AND package_version=$3",[userId,id,version]);if(drop)await c.query("DELETE FROM review_progress WHERE user_id=$1 AND package_id=$2 AND package_version=$3",[userId,id,version]);await c.query("COMMIT")}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
export async function loadUserReviewStates(pool:Pool,userId:string):Promise<ReviewItemState[]>{const rows=(await pool.query<any>("SELECT * FROM review_progress WHERE user_id=$1 ORDER BY next_review_at,package_id,item_id",[userId])).rows;return rows.map(rowState)}
export async function ensureUserReviewState(pool:Pool,userId:string,i:ReviewItemIdentity,now:string){const s=createInitialReviewState(i,now);await upsertState(pool,userId,s);return s}
export async function recordUserReview(pool:Pool,userId:string,i:ReviewItemIdentity,rating:ReviewRating,at:string){const c=await pool.connect();try{await c.query("BEGIN");const initial=createInitialReviewState(i,at);await c.query("INSERT INTO review_progress(user_id,package_id,package_version,source_path,item_id,first_seen_at,next_review_at,review_count,lapse_count,interval_days,ease_factor,status) VALUES($1,$2,$3,$4,$5,$6,$7,0,0,0,2.5,'new') ON CONFLICT DO NOTHING",[userId,i.packageId,i.packageVersion,i.sourcePath??"",i.itemId,initial.firstSeenAt,initial.nextReviewAt]);const q=await c.query<any>("SELECT * FROM review_progress WHERE user_id=$1 AND package_id=$2 AND package_version=$3 AND source_path=$4 AND item_id=$5 FOR UPDATE",[userId,i.packageId,i.packageVersion,i.sourcePath??"",i.itemId]),current=rowState(q.rows[0]),out=recordReviewOutcome(current,rating,at);await upsertState(c,userId,out.state);await c.query("INSERT INTO review_history(user_id,package_id,package_version,source_path,item_id,rating,reviewed_at,previous_state,next_state) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)",[userId,i.packageId,i.packageVersion,i.sourcePath??"",i.itemId,rating,at,out.event.previousState,out.event.nextState]);await c.query("COMMIT");return out}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
async function upsertState(db:Pool|PoolClient,userId:string,s:ReviewItemState){await db.query("INSERT INTO review_progress(user_id,package_id,package_version,source_path,item_id,first_seen_at,last_reviewed_at,next_review_at,review_count,lapse_count,interval_days,ease_factor,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(user_id,package_id,package_version,source_path,item_id) DO UPDATE SET last_reviewed_at=EXCLUDED.last_reviewed_at,next_review_at=EXCLUDED.next_review_at,review_count=EXCLUDED.review_count,lapse_count=EXCLUDED.lapse_count,interval_days=EXCLUDED.interval_days,ease_factor=EXCLUDED.ease_factor,status=EXCLUDED.status,updated_at=now()",[userId,s.packageId,s.packageVersion,s.sourcePath??"",s.itemId,s.firstSeenAt,s.lastReviewedAt??null,s.nextReviewAt,s.reviewCount,s.lapseCount,s.intervalDays,s.easeFactor,s.status])}
const iso=(v:unknown)=>new Date(v as any).toISOString().replace(/\.\d{3}Z$/u,"Z");
const rowState=(r:any):ReviewItemState=>({packageId:r.package_id,packageVersion:r.package_version,...(r.source_path?{sourcePath:r.source_path}:{}),itemId:r.item_id,firstSeenAt:iso(r.first_seen_at),...(r.last_reviewed_at?{lastReviewedAt:iso(r.last_reviewed_at)}:{}),nextReviewAt:iso(r.next_review_at),reviewCount:r.review_count,lapseCount:r.lapse_count,intervalDays:r.interval_days,easeFactor:r.ease_factor,status:r.status});
