*
!whacksmacker/
!whacksmacker/**
whacksmacker/node_modules
whacksmacker/dist
whacksmacker/coverage
whacksmacker/.cache
!dutch-curriculum/
!dutch-curriculum/**
!vietnamese-curriculum/
!vietnamese-curriculum/**

!japanese-curriculum/
!japanese-curriculum/**
!korean-curriculum/
!korean-curriculum/**
