// Generated by scripts/sync-linguistic-terminology.mjs. Do not edit by hand.

import type { LinguisticTerminologySnapshot } from "./linguistic-terminology";

export const linguisticTerminologySnapshot: LinguisticTerminologySnapshot = {
  "sourceRepository": "linguistic-terminology",
  "sourceCommit": "d2612e2dcef8204b43d1927a7cb6e3911cb8cc6e",
  "terms": [
    {
      "id": "learning.active-production",
      "heading": "Active Production",
      "aliases": [
        "productive use"
      ],
      "category": "Language learning",
      "sourceFile": "terms/language-learning.md",
      "sourceAnchor": "active-production",
      "shortDefinition": "Using language forms to produce an answer, utterance, or text.",
      "explanation": "Active production can be highly constrained or open-ended. Curriculum notes should distinguish short structural answers from free composition.",
      "relatedTerms": [
        {
          "label": "controlled recall",
          "target": "#controlled-recall"
        },
        {
          "label": "free writing",
          "target": "#free-writing"
        }
      ]
    },
    {
      "id": "phonology.allophone",
      "heading": "Allophone",
      "aliases": [
        "contextual sound variant"
      ],
      "category": "Phonetics and phonology",
      "sourceFile": "terms/phonetics-and-phonology.md",
      "sourceAnchor": "allophone",
      "shortDefinition": "A pronunciation variant of a phoneme.",
      "explanation": "Allophones often occur in predictable environments. Speakers may hear them as the same sound category even if they are physically different.",
      "relatedTerms": [
        {
          "label": "phoneme",
          "target": "#phoneme"
        },
        {
          "label": "sound change",
          "target": "#sound-change"
        }
      ]
    },
    {
      "id": "writing.alphabet",
      "heading": "Alphabet",
      "aliases": [
        "alphabetic script"
      ],
      "category": "Writing systems",
      "sourceFile": "terms/writing-systems.md",
      "sourceAnchor": "alphabet",
      "shortDefinition": "A writing system where letters commonly represent consonants and vowels.",
      "explanation": "Alphabetic systems vary widely. The same letter may represent different sounds in different languages.",
      "relatedTerms": [
        {
          "label": "letter",
          "target": "#letter"
        },
        {
          "label": "grapheme",
          "target": "#grapheme"
        },
        {
          "label": "script",
          "target": "#script"
        }
      ]
    },
    {
      "id": "korean.aspirated-consonant",
      "heading": "Aspirated Consonant",
      "aliases": [
        "aspirated Korean consonant"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "aspirated-consonant",
      "shortDefinition": "A Korean consonant category pronounced with strong aspiration.",
      "explanation": "Korean aspirated consonants contrast with plain and tense consonants. They should be taught as part of the Korean sound and writing system, not as English lookalikes.",
      "relatedTerms": [
        {
          "label": "aspirated consonant",
          "target": "phonetics-and-phonology.md#aspirated-consonant"
        },
        {
          "label": "tense consonant",
          "target": "#tense-consonant"
        }
      ]
    },
    {
      "id": "phonology.aspirated-consonant",
      "heading": "Aspirated Consonant",
      "aliases": [
        "aspirate"
      ],
      "category": "Phonetics and phonology",
      "sourceFile": "terms/phonetics-and-phonology.md",
      "sourceAnchor": "aspirated-consonant",
      "shortDefinition": "A consonant pronounced with a noticeable release of breath.",
      "explanation": "Korean has consonants traditionally described as aspirated. They contrast with plain and tense consonants.",
      "relatedTerms": [
        {
          "label": "aspiration",
          "target": "#aspiration"
        },
        {
          "label": "tense consonant",
          "target": "#tense-consonant"
        }
      ]
    },
    {
      "id": "phonology.aspiration",
      "heading": "Aspiration",
      "aliases": [
        "breath release"
      ],
      "category": "Phonetics and phonology",
      "sourceFile": "terms/phonetics-and-phonology.md",
      "sourceAnchor": "aspiration",
      "shortDefinition": "A burst of breath that accompanies some consonants.",
      "explanation": "Aspiration is a phonetic feature. In some languages it distinguishes words; in others it is only a predictable pronunciation detail.",
      "relatedTerms": [
        {
          "label": "aspirated consonant",
          "target": "#aspirated-consonant"
        },
        {
          "label": "consonant",
          "target": "#consonant"
        }
      ]
    },
    {
      "id": "phonology.assimilation",
      "heading": "Assimilation",
      "aliases": [
        "sound assimilation"
      ],
      "category": "Phonetics and phonology",
      "sourceFile": "terms/phonetics-and-phonology.md",
      "sourceAnchor": "assimilation",
      "shortDefinition": "A sound change where one sound becomes more like a nearby sound.",
      "explanation": "Assimilation can affect place of articulation, voicing, nasality, or other features. It is common across languages.",
      "relatedTerms": [
        {
          "label": "nasal assimilation",
          "target": "#nasal-assimilation"
        },
        {
          "label": "sound change",
          "target": "#sound-change"
        }
      ]
    },
    {
      "id": "korean.basic-batchim",
      "heading": "Basic 받침",
      "aliases": [
        "simple final consonant"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "basic-받침",
      "shortDefinition": "A 받침 written with a single consonant jamo.",
      "explanation": "Basic 받침 is a pedagogical label for single written final consonants. The actual final pronunciation may still be affected by Korean final-sound rules.",
      "relatedTerms": [
        {
          "label": "받침",
          "target": "#받침"
        },
        {
          "label": "compound 받침",
          "target": "#compound-받침"
        }
      ]
    },
    {
      "id": "writing.coda",
      "heading": "Coda",
      "aliases": [
        "final syllable position"
      ],
      "category": "Writing systems",
      "sourceFile": "terms/writing-systems.md",
      "sourceAnchor": "coda",
      "shortDefinition": "The consonant or consonants after a syllable nucleus.",
      "explanation": "Coda is a syllable position. In Korean pedagogy it is closely related to the written final-consonant position called 받침.",
      "relatedTerms": [
        {
          "label": "final consonant",
          "target": "#final-consonant"
        },
        {
          "label": "받침",
          "target": "korean.md#받침"
        },
        {
          "label": "syllable",
          "target": "#syllable"
        }
      ]
    },
    {
      "id": "korean.compound-batchim",
      "heading": "Compound 받침",
      "aliases": [
        "double final consonant",
        "final consonant cluster"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "compound-받침",
      "shortDefinition": "A 받침 written with two consonant jamo.",
      "explanation": "Compound 받침 are written clusters in final position. Their pronunciation depends on context and does not simply pronounce both consonants in all environments.",
      "relatedTerms": [
        {
          "label": "받침",
          "target": "#받침"
        },
        {
          "label": "basic 받침",
          "target": "#basic-받침"
        },
        {
          "label": "resyllabification",
          "target": "#resyllabification"
        }
      ]
    },
    {
      "id": "phonology.consonant",
      "heading": "Consonant",
      "aliases": [
        "consonant sound"
      ],
      "category": "Phonetics and phonology",
      "sourceFile": "terms/phonetics-and-phonology.md",
      "sourceAnchor": "consonant",
      "shortDefinition": "A speech sound made with a significant narrowing or closure in the vocal tract.",
      "explanation": "Consonants often occur at the edges of syllables, but languages differ in how consonants are arranged and written.",
      "relatedTerms": [
        {
          "label": "vowel",
          "target": "#vowel"
        },
        {
          "label": "onset",
          "target": "writing-systems.md#onset"
        },
        {
          "label": "coda",
          "target": "writing-systems.md#coda"
        }
      ]
    },
    {
      "id": "korean.consonant-carry-over",
      "heading": "Consonant Carry-Over",
      "aliases": [
        "carry-over before a following vowel"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "consonant-carry-over",
      "shortDefinition": "An informal teaching label for a final consonant being pronounced with a following vowel-initial syllable.",
      "explanation": "The more technical term is resyllabification. The informal label can remain useful for learners if the technical relationship is explained.",
      "relatedTerms": [
        {
          "label": "resyllabification",
          "target": "#resyllabification"
        },
        {
          "label": "받침",
          "target": "#받침"
        }
      ]
    },
    {
      "id": "korean.consonant-jamo",
      "heading": "Consonant Jamo",
      "aliases": [
        "consonant letter"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "consonant-jamo",
      "shortDefinition": "A Hangul jamo used to write a consonant element.",
      "explanation": "Consonant jamo can appear in initial or final written positions. Their pronunciation may differ by position and context.",
      "relatedTerms": [
        {
          "label": "jamo",
          "target": "#jamo"
        },
        {
          "label": "initial ㅇ",
          "target": "#initial-ㅇ"
        },
        {
          "label": "받침",
          "target": "#받침"
        }
      ]
    },
    {
      "id": "learning.constrained-writing",
      "heading": "Constrained Writing",
      "aliases": [
        "mild writing"
      ],
      "category": "Language learning",
      "sourceFile": "terms/language-learning.md",
      "sourceAnchor": "constrained-writing",
      "shortDefinition": "A short written-response task limited to known or currently introduced material.",
      "explanation": "In the curriculum-builder methodology, constrained writing begins early. It requires the learner to produce the current grammar structure without becoming free composition.",
      "relatedTerms": [
        {
          "label": "controlled recall",
          "target": "#controlled-recall"
        },
        {
          "label": "free writing",
          "target": "#free-writing"
        },
        {
          "label": "cumulative ledger",
          "target": "#cumulative-ledger"
        }
      ]
    },
    {
      "id": "pragmatics.context",
      "heading": "Context",
      "aliases": [
        "situational context"
      ],
      "category": "Semantics and pragmatics",
      "sourceFile": "terms/semantics-and-pragmatics.md",
      "sourceAnchor": "context",
      "shortDefinition": "The situation, participants, and shared information that shape meaning.",
      "explanation": "Context can determine what is omitted, what is polite, what a pronoun refers to, or why one translation is more natural than another.",
      "relatedTerms": [
        {
          "label": "pragmatics",
          "target": "#pragmatics"
        },
        {
          "label": "natural translation",
          "target": "#natural-translation"
        }
      ]
    },
    {
      "id": "learning.controlled-recall",
      "heading": "Controlled Recall",
      "aliases": [
        "prompted recall"
      ],
      "category": "Language learning",
      "sourceFile": "terms/language-learning.md",
      "sourceAnchor": "controlled-recall",
      "shortDefinition": "Producing or identifying information when a prompt strongly limits what is required.",
      "explanation": "Controlled recall is narrower than free production. A constrained written answer can test controlled recall.",
      "relatedTerms": [
        {
          "label": "constrained writing",
          "target": "#constrained-writing"
        },
        {
          "label": "active production",
          "target": "#active-production"
        }
      ]
    },
    {
      "id": "learning.cumulative-ledger",
      "heading": "Cumulative Ledger",
      "aliases": [
        "legality ledger"
      ],
      "category": "Language learning",
      "sourceFile": "terms/language-learning.md",
      "sourceAnchor": "cumulative-ledger",
      "shortDefinition": "A record of what language material has been introduced and how it may be used.",
      "explanation": "The ledger supports strict cumulative curriculum design by showing whether a text, question, or expected answer uses only legal material.",
      "relatedTerms": [
        {
          "label": "cumulative review",
          "target": "#cumulative-review"
        },
        {
          "label": "constrained writing",
          "target": "#constrained-writing"
        }
      ]
    },
    {
      "id": "learning.cumulative-review",
      "heading": "Cumulative Review",
      "aliases": [
        "cumulative recombination"
      ],
      "category": "Language learning",
      "sourceFile": "terms/language-learning.md",
      "sourceAnchor": "cumulative-review",
      "shortDefinition": "Review that recombines previously taught material.",
      "explanation": "Cumulative review should not introduce hidden new vocabulary or grammar. It strengthens access to earlier material.",
      "relatedTerms": [
        {
          "label": "cumulative ledger",
          "target": "#cumulative-ledger"
        },
        {
          "label": "recognition",
          "target": "#recognition"
        }
      ]
    },
    {
      "id": "learning.decoding",
      "heading": "Decoding",
      "aliases": [
        "written decoding"
      ],
      "category": "Language learning",
      "sourceFile": "terms/language-learning.md",
      "sourceAnchor": "decoding",
      "shortDefinition": "Working out a written form from known writing-system and language knowledge.",
      "explanation": "Decoding can involve recognizing letters, characters, syllable blocks, spelling patterns, and known vocabulary.",
      "relatedTerms": [
        {
          "label": "reading drill",
          "target": "#reading-drill"
        },
        {
          "label": "writing system",
          "target": "writing-systems.md#writing-system"
        }
      ]
    },
    {
      "id": "writing.diacritic",
      "heading": "Diacritic",
      "aliases": [
        "mark"
      ],
      "category": "Writing systems",
      "sourceFile": "terms/writing-systems.md",
      "sourceAnchor": "diacritic",
      "shortDefinition": "A mark added to a written symbol to modify its value or function.",
      "explanation": "Diacritics may mark pronunciation, tone, stress, vowel quality, or other distinctions depending on the writing system.",
      "relatedTerms": [
        {
          "label": "grapheme",
          "target": "#grapheme"
        },
        {
          "label": "orthography",
          "target": "#orthography"
        }
      ]
    },
    {
      "id": "core.dialect",
      "heading": "Dialect",
      "aliases": [
        "variety"
      ],
      "category": "Core linguistics",
      "sourceFile": "terms/core-linguistics.md",
      "sourceAnchor": "dialect",
      "shortDefinition": "A language variety associated with a region, community, or social group.",
      "explanation": "Dialects may differ in pronunciation, vocabulary, grammar, and usage. The boundary between a language and a dialect can involve social and political factors as well as linguistic ones.",
      "relatedTerms": [
        {
          "label": "language",
          "target": "#language"
        },
        {
          "label": "register",
          "target": "#register"
        }
      ]
    },
    {
      "id": "morphology.ending",
      "heading": "Ending",
      "aliases": [
        "suffix",
        "ending form"
      ],
      "category": "Morphology and syntax",
      "sourceFile": "terms/morphology-and-syntax.md",
      "sourceAnchor": "ending",
      "shortDefinition": "A form attached at the end of another form to express grammatical meaning.",
      "explanation": "Endings may mark tense, mood, politeness, sentence type, or other categories. The exact term depends on the language and tradition.",
      "relatedTerms": [
        {
          "label": "inflection",
          "target": "#inflection"
        },
        {
          "label": "morpheme",
          "target": "core-linguistics.md#morpheme"
        }
      ]
    },
    {
      "id": "writing.final-consonant",
      "heading": "Final Consonant",
      "aliases": [
        "final"
      ],
      "category": "Writing systems",
      "sourceFile": "terms/writing-systems.md",
      "sourceAnchor": "final-consonant",
      "shortDefinition": "A consonant at the end of a syllable or written syllable unit.",
      "explanation": "Final consonant can describe a phonological coda or a written final position. These are related but not always identical.",
      "relatedTerms": [
        {
          "label": "coda",
          "target": "#coda"
        },
        {
          "label": "받침",
          "target": "korean.md#받침"
        }
      ]
    },
    {
      "id": "korean.final-ieung",
      "heading": "Final ㅇ",
      "aliases": [
        "ㅇ 받침"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "final-ㅇ",
      "shortDefinition": "The written ㅇ used in final position to represent the consonant /ŋ/.",
      "explanation": "Initial ㅇ and final ㅇ use the same written jamo, but they do not have the same phonetic function. Initial ㅇ is silent in modern spelling, while final ㅇ is pronounced as /ŋ/.",
      "relatedTerms": [
        {
          "label": "initial ㅇ",
          "target": "#initial-ㅇ"
        },
        {
          "label": "받침",
          "target": "#받침"
        },
        {
          "label": "final consonant",
          "target": "writing-systems.md#final-consonant"
        }
      ]
    },
    {
      "id": "core.fixed-expression",
      "heading": "Fixed Expression",
      "aliases": [
        "formulaic expression"
      ],
      "category": "Core linguistics",
      "sourceFile": "terms/core-linguistics.md",
      "sourceAnchor": "fixed-expression",
      "shortDefinition": "A phrase learned as a unit because its form or meaning is not freely built each time.",
      "explanation": "Fixed expressions may contain ordinary words, but the whole expression has a conventional use. Greetings and polite formulas often behave this way.",
      "relatedTerms": [
        {
          "label": "vocabulary",
          "target": "#vocabulary"
        },
        {
          "label": "productive form",
          "target": "morphology-and-syntax.md#productive-form"
        }
      ]
    },
    {
      "id": "learning.free-writing",
      "heading": "Free Writing",
      "aliases": [
        "free composition"
      ],
      "category": "Language learning",
      "sourceFile": "terms/language-learning.md",
      "sourceAnchor": "free-writing",
      "shortDefinition": "Writing where the learner chooses content and language with relatively little restriction.",
      "explanation": "Free writing is deferred until the learner has enough legal material and control to compose independently.",
      "relatedTerms": [
        {
          "label": "constrained writing",
          "target": "#constrained-writing"
        },
        {
          "label": "active production",
          "target": "#active-production"
        }
      ]
    },
    {
      "id": "phonology.glide",
      "heading": "Glide",
      "aliases": [
        "semivowel"
      ],
      "category": "Phonetics and phonology",
      "sourceFile": "terms/phonetics-and-phonology.md",
      "sourceAnchor": "glide",
      "shortDefinition": "A vowel-like sound that moves quickly into or out of a syllable nucleus.",
      "explanation": "Glide and semivowel are closely related terms. Some traditions use them interchangeably, while others reserve glide for the phonetic movement and semivowel for the sound's consonant-like role.",
      "relatedTerms": [
        {
          "label": "semivowel",
          "target": "#semivowel"
        },
        {
          "label": "vowel",
          "target": "#vowel"
        }
      ]
    },
    {
      "id": "core.grammar",
      "heading": "Grammar",
      "aliases": [
        "grammatical system"
      ],
      "category": "Core linguistics",
      "sourceFile": "terms/core-linguistics.md",
      "sourceAnchor": "grammar",
      "shortDefinition": "The patterns that organize meaningful forms in a language.",
      "explanation": "Grammar includes how words change form, how they combine, and how sentences express relationships such as time, role, questionhood, or politeness. It is not limited to school-style rules.",
      "relatedTerms": [
        {
          "label": "morphology",
          "target": "morphology-and-syntax.md#morphology"
        },
        {
          "label": "syntax",
          "target": "morphology-and-syntax.md#syntax"
        },
        {
          "label": "grammatical structure",
          "target": "morphology-and-syntax.md#grammatical-structure"
        }
      ]
    },
    {
      "id": "syntax.grammatical-structure",
      "heading": "Grammatical Structure",
      "aliases": [
        "grammar structure"
      ],
      "category": "Morphology and syntax",
      "sourceFile": "terms/morphology-and-syntax.md",
      "sourceAnchor": "grammatical-structure",
      "shortDefinition": "A reusable pattern that expresses a grammatical function or relationship.",
      "explanation": "In curriculum design, a grammatical structure is a teachable unit such as a sentence pattern, particle use, ending, or inflectional pattern.",
      "relatedTerms": [
        {
          "label": "sentence pattern",
          "target": "#sentence-pattern"
        },
        {
          "label": "productive form",
          "target": "#productive-form"
        }
      ]
    },
    {
      "id": "writing.grapheme",
      "heading": "Grapheme",
      "aliases": [
        "written contrastive unit"
      ],
      "category": "Writing systems",
      "sourceFile": "terms/writing-systems.md",
      "sourceAnchor": "grapheme",
      "shortDefinition": "A writing-system unit that distinguishes written forms.",
      "explanation": "A grapheme may be a single letter, a character, a diacritic combination, or another meaningful written unit depending on the script.",
      "relatedTerms": [
        {
          "label": "letter",
          "target": "#letter"
        },
        {
          "label": "orthography",
          "target": "#orthography"
        }
      ]
    },
    {
      "id": "korean.hangul",
      "heading": "Hangul",
      "aliases": [
        "Hangeul",
        "한글"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "hangul",
      "shortDefinition": "The Korean writing system.",
      "explanation": "Hangul writes Korean using letters called jamo arranged into syllable blocks. It is a writing system, not the Korean language itself.",
      "relatedTerms": [
        {
          "label": "jamo",
          "target": "#jamo"
        },
        {
          "label": "syllable block",
          "target": "#syllable-block"
        },
        {
          "label": "script",
          "target": "writing-systems.md#script"
        }
      ]
    },
    {
      "id": "morphology.inflection",
      "heading": "Inflection",
      "aliases": [
        "inflected form"
      ],
      "category": "Morphology and syntax",
      "sourceFile": "terms/morphology-and-syntax.md",
      "sourceAnchor": "inflection",
      "shortDefinition": "A change in form that expresses grammatical information.",
      "explanation": "Inflection may mark tense, case, number, politeness, person, or other grammatical categories. Languages differ greatly in how much inflection they use.",
      "relatedTerms": [
        {
          "label": "ending",
          "target": "#ending"
        },
        {
          "label": "morpheme",
          "target": "core-linguistics.md#morpheme"
        }
      ]
    },
    {
      "id": "writing.initial-consonant",
      "heading": "Initial Consonant",
      "aliases": [
        "initial"
      ],
      "category": "Writing systems",
      "sourceFile": "terms/writing-systems.md",
      "sourceAnchor": "initial-consonant",
      "shortDefinition": "A consonant at the beginning of a syllable or written syllable unit.",
      "explanation": "The term may describe a sound position or a written position. Curriculum notes should specify which one is meant.",
      "relatedTerms": [
        {
          "label": "onset",
          "target": "#onset"
        },
        {
          "label": "consonant",
          "target": "phonetics-and-phonology.md#consonant"
        }
      ]
    },
    {
      "id": "korean.initial-ieung",
      "heading": "Initial ㅇ",
      "aliases": [
        "silent initial ㅇ"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "initial-ㅇ",
      "shortDefinition": "The written ㅇ used as a silent placeholder at the beginning of a modern Korean syllable block.",
      "explanation": "Modern Korean syllable spelling requires an initial position. When a syllable begins with a vowel sound, ㅇ fills that written initial position without adding an initial consonant sound.",
      "relatedTerms": [
        {
          "label": "final ㅇ",
          "target": "#final-ㅇ"
        },
        {
          "label": "jamo",
          "target": "#jamo"
        },
        {
          "label": "initial consonant",
          "target": "writing-systems.md#initial-consonant"
        }
      ]
    },
    {
      "id": "korean.jamo",
      "heading": "Jamo",
      "aliases": [
        "자모"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "jamo",
      "shortDefinition": "A Hangul letter.",
      "explanation": "Jamo are the basic written elements of Hangul. They include consonant jamo and vowel jamo and are arranged into syllable blocks.",
      "relatedTerms": [
        {
          "label": "Hangul",
          "target": "#hangul"
        },
        {
          "label": "vowel jamo",
          "target": "#vowel-jamo"
        },
        {
          "label": "consonant jamo",
          "target": "#consonant-jamo"
        }
      ]
    },
    {
      "id": "core.language",
      "heading": "Language",
      "aliases": [
        "language system"
      ],
      "category": "Core linguistics",
      "sourceFile": "terms/core-linguistics.md",
      "sourceAnchor": "language",
      "shortDefinition": "A structured system that people use to communicate meaning.",
      "explanation": "A language includes sounds or signs, words, grammar, meanings, social conventions, and ways of using those resources in context. It is not only a list of words.",
      "relatedTerms": [
        {
          "label": "grammar",
          "target": "#grammar"
        },
        {
          "label": "vocabulary",
          "target": "#vocabulary"
        },
        {
          "label": "register",
          "target": "#register"
        }
      ]
    },
    {
      "id": "writing.letter",
      "heading": "Letter",
      "aliases": [
        "alphabetic character"
      ],
      "category": "Writing systems",
      "sourceFile": "terms/writing-systems.md",
      "sourceAnchor": "letter",
      "shortDefinition": "A written symbol used as part of an alphabet or similar script.",
      "explanation": "A letter is a written unit, not a sound. The same letter can represent different sounds depending on language and context.",
      "relatedTerms": [
        {
          "label": "grapheme",
          "target": "#grapheme"
        },
        {
          "label": "speech sound",
          "target": "phonetics-and-phonology.md#speech-sound"
        }
      ]
    },
    {
      "id": "core.lexicon",
      "heading": "Lexicon",
      "aliases": [
        "mental dictionary"
      ],
      "category": "Core linguistics",
      "sourceFile": "terms/core-linguistics.md",
      "sourceAnchor": "lexicon",
      "shortDefinition": "The stored vocabulary of a language or a speaker.",
      "explanation": "The lexicon includes word forms, meanings, usage restrictions, pronunciation, and sometimes irregular grammatical information.",
      "relatedTerms": [
        {
          "label": "vocabulary",
          "target": "#vocabulary"
        },
        {
          "label": "morpheme",
          "target": "#morpheme"
        }
      ]
    },
    {
      "id": "semantics.literal-meaning",
      "heading": "Literal Meaning",
      "aliases": [
        "word-for-word meaning"
      ],
      "category": "Semantics and pragmatics",
      "sourceFile": "terms/semantics-and-pragmatics.md",
      "sourceAnchor": "literal-meaning",
      "shortDefinition": "The meaning obtained by closely following the forms used.",
      "explanation": "Literal meaning can help explain structure, but it may sound unnatural in translation.",
      "relatedTerms": [
        {
          "label": "natural translation",
          "target": "#natural-translation"
        },
        {
          "label": "semantics",
          "target": "#semantics"
        }
      ]
    },
    {
      "id": "korean.mccune-reischauer",
      "heading": "McCune-Reischauer",
      "aliases": [
        "MR romanization"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "mccune-reischauer",
      "shortDefinition": "An older romanization system for Korean.",
      "explanation": "McCune-Reischauer uses marks such as apostrophes and breves to represent distinctions that Revised Romanization handles differently.",
      "relatedTerms": [
        {
          "label": "romanization",
          "target": "writing-systems.md#romanization"
        },
        {
          "label": "Revised Romanization",
          "target": "#revised-romanization"
        }
      ]
    },
    {
      "id": "core.morpheme",
      "heading": "Morpheme",
      "aliases": [
        "meaningful form"
      ],
      "category": "Core linguistics",
      "sourceFile": "terms/core-linguistics.md",
      "sourceAnchor": "morpheme",
      "shortDefinition": "The smallest language form that carries meaning or grammatical function.",
      "explanation": "A morpheme may be a whole word or a smaller part of a word. For example, an ending can mark tense, politeness, or grammatical role.",
      "relatedTerms": [
        {
          "label": "morphology",
          "target": "morphology-and-syntax.md#morphology"
        },
        {
          "label": "inflection",
          "target": "morphology-and-syntax.md#inflection"
        },
        {
          "label": "ending",
          "target": "morphology-and-syntax.md#ending"
        }
      ]
    },
    {
      "id": "morphology.morphology",
      "heading": "Morphology",
      "aliases": [
        "word structure"
      ],
      "category": "Morphology and syntax",
      "sourceFile": "terms/morphology-and-syntax.md",
      "sourceAnchor": "morphology",
      "shortDefinition": "The study of meaningful forms inside words and word-like units.",
      "explanation": "Morphology includes roots, endings, inflections, particles in some traditions, and how forms combine to express grammatical meaning.",
      "relatedTerms": [
        {
          "label": "morpheme",
          "target": "core-linguistics.md#morpheme"
        },
        {
          "label": "inflection",
          "target": "#inflection"
        }
      ]
    },
    {
      "id": "phonology.nasal-assimilation",
      "heading": "Nasal Assimilation",
      "aliases": [
        "nasalization by context"
      ],
      "category": "Phonetics and phonology",
      "sourceFile": "terms/phonetics-and-phonology.md",
      "sourceAnchor": "nasal-assimilation",
      "shortDefinition": "Assimilation where a sound becomes nasal or more nasal because of a nearby nasal sound.",
      "explanation": "Nasal assimilation is important in Korean pronunciation because some written consonant sequences are pronounced with nasal sounds.",
      "relatedTerms": [
        {
          "label": "assimilation",
          "target": "#assimilation"
        },
        {
          "label": "consonant",
          "target": "#consonant"
        }
      ]
    },
    {
      "id": "semantics.natural-translation",
      "heading": "Natural Translation",
      "aliases": [
        "idiomatic translation"
      ],
      "category": "Semantics and pragmatics",
      "sourceFile": "terms/semantics-and-pragmatics.md",
      "sourceAnchor": "natural-translation",
      "shortDefinition": "A translation that expresses the intended meaning naturally in the target translation language.",
      "explanation": "A natural translation may not match the source structure word for word. Curriculum notes should distinguish natural translation from structural explanation.",
      "relatedTerms": [
        {
          "label": "literal meaning",
          "target": "#literal-meaning"
        },
        {
          "label": "pragmatics",
          "target": "#pragmatics"
        }
      ]
    },
    {
      "id": "writing.nucleus",
      "heading": "Nucleus",
      "aliases": [
        "syllable nucleus"
      ],
      "category": "Writing systems",
      "sourceFile": "terms/writing-systems.md",
      "sourceAnchor": "nucleus",
      "shortDefinition": "The central part of a syllable, usually a vowel.",
      "explanation": "The nucleus carries the core of the syllable. Some languages allow syllabic consonants, so \"usually a vowel\" should not be treated as universal.",
      "relatedTerms": [
        {
          "label": "vowel",
          "target": "phonetics-and-phonology.md#vowel"
        },
        {
          "label": "syllable",
          "target": "#syllable"
        }
      ]
    },
    {
      "id": "writing.onset",
      "heading": "Onset",
      "aliases": [
        "initial syllable position"
      ],
      "category": "Writing systems",
      "sourceFile": "terms/writing-systems.md",
      "sourceAnchor": "onset",
      "shortDefinition": "The consonant or consonants before a syllable nucleus.",
      "explanation": "Onset is a syllable position. It is not automatically the same as the first written symbol in every writing system.",
      "relatedTerms": [
        {
          "label": "nucleus",
          "target": "#nucleus"
        },
        {
          "label": "coda",
          "target": "#coda"
        },
        {
          "label": "initial consonant",
          "target": "#initial-consonant"
        }
      ]
    },
    {
      "id": "writing.orthography",
      "heading": "Orthography",
      "aliases": [
        "spelling system"
      ],
      "category": "Writing systems",
      "sourceFile": "terms/writing-systems.md",
      "sourceAnchor": "orthography",
      "shortDefinition": "The conventional spelling and writing rules of a language.",
      "explanation": "Orthography includes how sounds, words, spaces, punctuation, capitalization, and sometimes morphology are represented in writing.",
      "relatedTerms": [
        {
          "label": "writing system",
          "target": "#writing-system"
        },
        {
          "label": "script",
          "target": "#script"
        },
        {
          "label": "grapheme",
          "target": "#grapheme"
        }
      ]
    },
    {
      "id": "phonology.palatalization",
      "heading": "Palatalization",
      "aliases": [
        "palatal sound change"
      ],
      "category": "Phonetics and phonology",
      "sourceFile": "terms/phonetics-and-phonology.md",
      "sourceAnchor": "palatalization",
      "shortDefinition": "A sound change where a sound is pronounced closer to the hard palate.",
      "explanation": "Palatalization often happens near front vowels or y-like sounds. It can create sounds similar to English *ch* or *j* in some languages.",
      "relatedTerms": [
        {
          "label": "sound change",
          "target": "#sound-change"
        },
        {
          "label": "semivowel",
          "target": "#semivowel"
        }
      ]
    },
    {
      "id": "morphology.particle",
      "heading": "Particle",
      "aliases": [
        "function particle"
      ],
      "category": "Morphology and syntax",
      "sourceFile": "terms/morphology-and-syntax.md",
      "sourceAnchor": "particle",
      "shortDefinition": "A short grammatical form that marks relationships or functions.",
      "explanation": "Particles may mark topic, subject, object, direction, emphasis, questionhood, or other meanings depending on the language.",
      "relatedTerms": [
        {
          "label": "ending",
          "target": "#ending"
        },
        {
          "label": "grammatical structure",
          "target": "#grammatical-structure"
        }
      ]
    },
    {
      "id": "phonology.phoneme",
      "heading": "Phoneme",
      "aliases": [
        "contrastive sound"
      ],
      "category": "Phonetics and phonology",
      "sourceFile": "terms/phonetics-and-phonology.md",
      "sourceAnchor": "phoneme",
      "shortDefinition": "A sound category that can distinguish meaning in a particular language.",
      "explanation": "Two sounds may be separate phonemes in one language but not in another. Phonemes belong to a language's sound system, not to universal spelling.",
      "relatedTerms": [
        {
          "label": "allophone",
          "target": "#allophone"
        },
        {
          "label": "speech sound",
          "target": "#speech-sound"
        }
      ]
    },
    {
      "id": "phonology.phonetics",
      "heading": "Phonetics",
      "aliases": [
        "speech phonetics"
      ],
      "category": "Phonetics and phonology",
      "sourceFile": "terms/phonetics-and-phonology.md",
      "sourceAnchor": "phonetics",
      "shortDefinition": "The study of how speech sounds are produced, transmitted, and perceived.",
      "explanation": "Phonetics describes the physical side of speech, such as tongue position, airflow, voicing, and acoustic properties.",
      "relatedTerms": [
        {
          "label": "phonology",
          "target": "#phonology"
        },
        {
          "label": "speech sound",
          "target": "#speech-sound"
        }
      ]
    },
    {
      "id": "phonology.phonology",
      "heading": "Phonology",
      "aliases": [
        "sound system"
      ],
      "category": "Phonetics and phonology",
      "sourceFile": "terms/phonetics-and-phonology.md",
      "sourceAnchor": "phonology",
      "shortDefinition": "The study of how sounds function within a language.",
      "explanation": "Phonology explains which sound differences matter in a language and how sounds change in context.",
      "relatedTerms": [
        {
          "label": "phonetics",
          "target": "#phonetics"
        },
        {
          "label": "phoneme",
          "target": "#phoneme"
        },
        {
          "label": "sound change",
          "target": "#sound-change"
        }
      ]
    },
    {
      "id": "pragmatics.politeness",
      "heading": "Politeness",
      "aliases": [
        "politeness marking"
      ],
      "category": "Semantics and pragmatics",
      "sourceFile": "terms/semantics-and-pragmatics.md",
      "sourceAnchor": "politeness",
      "shortDefinition": "Language choices that manage respect, distance, familiarity, or social relationship.",
      "explanation": "Politeness may be expressed through vocabulary, endings, pronouns, titles, word order, or indirectness depending on the language.",
      "relatedTerms": [
        {
          "label": "speech level",
          "target": "#speech-level"
        },
        {
          "label": "register",
          "target": "core-linguistics.md#register"
        }
      ]
    },
    {
      "id": "pragmatics.pragmatics",
      "heading": "Pragmatics",
      "aliases": [
        "language use in context"
      ],
      "category": "Semantics and pragmatics",
      "sourceFile": "terms/semantics-and-pragmatics.md",
      "sourceAnchor": "pragmatics",
      "shortDefinition": "The study of how context affects language use and interpretation.",
      "explanation": "Pragmatics includes politeness, implication, social meaning, shared knowledge, and why a natural translation may differ from a literal one.",
      "relatedTerms": [
        {
          "label": "context",
          "target": "#context"
        },
        {
          "label": "politeness",
          "target": "#politeness"
        }
      ]
    },
    {
      "id": "morphology.productive-form",
      "heading": "Productive Form",
      "aliases": [
        "productive pattern"
      ],
      "category": "Morphology and syntax",
      "sourceFile": "terms/morphology-and-syntax.md",
      "sourceAnchor": "productive-form",
      "shortDefinition": "A form or pattern that can be used to create new valid examples.",
      "explanation": "A productive form can be reused beyond memorized examples. It contrasts with fixed expressions that must be learned as wholes.",
      "relatedTerms": [
        {
          "label": "fixed expression",
          "target": "core-linguistics.md#fixed-expression"
        },
        {
          "label": "grammatical structure",
          "target": "#grammatical-structure"
        }
      ]
    },
    {
      "id": "learning.reading-drill",
      "heading": "Reading Drill",
      "aliases": [
        "controlled reading practice"
      ],
      "category": "Language learning",
      "sourceFile": "terms/language-learning.md",
      "sourceAnchor": "reading-drill",
      "shortDefinition": "A focused exercise for recognizing and understanding written forms.",
      "explanation": "Reading drills should use material that is already known or explicitly introduced in the current unit.",
      "relatedTerms": [
        {
          "label": "decoding",
          "target": "#decoding"
        },
        {
          "label": "cumulative ledger",
          "target": "#cumulative-ledger"
        }
      ]
    },
    {
      "id": "learning.recognition",
      "heading": "Recognition",
      "aliases": [
        "receptive recognition"
      ],
      "category": "Language learning",
      "sourceFile": "terms/language-learning.md",
      "sourceAnchor": "recognition",
      "shortDefinition": "Understanding a form when it is seen or heard.",
      "explanation": "Recognition does not necessarily mean the learner can produce the form independently.",
      "relatedTerms": [
        {
          "label": "controlled recall",
          "target": "#controlled-recall"
        },
        {
          "label": "active production",
          "target": "#active-production"
        }
      ]
    },
    {
      "id": "core.register",
      "heading": "Register",
      "aliases": [
        "style level"
      ],
      "category": "Core linguistics",
      "sourceFile": "terms/core-linguistics.md",
      "sourceAnchor": "register",
      "shortDefinition": "A way of speaking or writing chosen for a social situation.",
      "explanation": "Register covers differences such as formal, informal, polite, technical, casual, or intimate language. It affects word choice, grammar, and sometimes pronunciation.",
      "relatedTerms": [
        {
          "label": "pragmatics",
          "target": "semantics-and-pragmatics.md#pragmatics"
        },
        {
          "label": "politeness",
          "target": "semantics-and-pragmatics.md#politeness"
        },
        {
          "label": "speech level",
          "target": "semantics-and-pragmatics.md#speech-level"
        }
      ]
    },
    {
      "id": "korean.resyllabification",
      "heading": "Resyllabification",
      "aliases": [
        "syllable redivision"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "resyllabification",
      "shortDefinition": "A pronunciation process where a consonant is associated with a following syllable.",
      "explanation": "In Korean, a written final consonant may be pronounced as the onset of a following vowel-initial syllable. This affects pronunciation, not the written spelling of the original syllable block.",
      "relatedTerms": [
        {
          "label": "consonant carry-over",
          "target": "#consonant-carry-over"
        },
        {
          "label": "coda",
          "target": "writing-systems.md#coda"
        },
        {
          "label": "onset",
          "target": "writing-systems.md#onset"
        }
      ]
    },
    {
      "id": "korean.revised-romanization",
      "heading": "Revised Romanization",
      "aliases": [
        "Revised Romanization of Korean"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "revised-romanization",
      "shortDefinition": "The official South Korean romanization system introduced in 2000.",
      "explanation": "Revised Romanization is the romanization system selected for limited header guidance in the Korean curriculum. It is a spelling conversion system, not a full pronunciation guide.",
      "relatedTerms": [
        {
          "label": "romanization",
          "target": "writing-systems.md#romanization"
        },
        {
          "label": "McCune-Reischauer",
          "target": "#mccune-reischauer"
        }
      ]
    },
    {
      "id": "writing.romanization",
      "heading": "Romanization",
      "aliases": [
        "romanized spelling"
      ],
      "category": "Writing systems",
      "sourceFile": "terms/writing-systems.md",
      "sourceAnchor": "romanization",
      "shortDefinition": "Writing a language with Roman letters.",
      "explanation": "Romanization may help learners identify or search for forms, but it is not the same as pronunciation. Different romanization systems can represent the same word differently.",
      "relatedTerms": [
        {
          "label": "transliteration",
          "target": "#transliteration"
        },
        {
          "label": "transcription",
          "target": "#transcription"
        },
        {
          "label": "Revised Romanization",
          "target": "korean.md#revised-romanization"
        }
      ]
    },
    {
      "id": "writing.script",
      "heading": "Script",
      "aliases": [
        "writing script"
      ],
      "category": "Writing systems",
      "sourceFile": "terms/writing-systems.md",
      "sourceAnchor": "script",
      "shortDefinition": "A set of written signs used to write one or more languages.",
      "explanation": "Latin, Cyrillic, Arabic, Devanagari, Chinese characters, and Hangul are scripts. A language may use more than one script, and a script may be used by many languages.",
      "relatedTerms": [
        {
          "label": "writing system",
          "target": "#writing-system"
        },
        {
          "label": "letter",
          "target": "#letter"
        },
        {
          "label": "grapheme",
          "target": "#grapheme"
        }
      ]
    },
    {
      "id": "semantics.semantics",
      "heading": "Semantics",
      "aliases": [
        "meaning"
      ],
      "category": "Semantics and pragmatics",
      "sourceFile": "terms/semantics-and-pragmatics.md",
      "sourceAnchor": "semantics",
      "shortDefinition": "The study of linguistic meaning.",
      "explanation": "Semantics concerns what words, forms, and sentences mean, apart from or together with context depending on the analysis.",
      "relatedTerms": [
        {
          "label": "literal meaning",
          "target": "#literal-meaning"
        },
        {
          "label": "natural translation",
          "target": "#natural-translation"
        }
      ]
    },
    {
      "id": "phonology.semivowel",
      "heading": "Semivowel",
      "aliases": [
        "glide"
      ],
      "category": "Phonetics and phonology",
      "sourceFile": "terms/phonetics-and-phonology.md",
      "sourceAnchor": "semivowel",
      "shortDefinition": "A speech sound produced with vowel-like articulation that functions more like a consonant in a syllable.",
      "explanation": "A semivowel has relatively little obstruction of airflow, like a vowel, but normally occurs at the edge of a syllable rather than as its central vowel. English sounds represented by *y* in *yes* and *w* in *we* are common examples.",
      "example": "The Korean y-vowels contain a glide before the main vowel.",
      "relatedTerms": [
        {
          "label": "glide",
          "target": "#glide"
        },
        {
          "label": "vowel",
          "target": "#vowel"
        },
        {
          "label": "consonant",
          "target": "#consonant"
        },
        {
          "label": "syllable",
          "target": "writing-systems.md#syllable"
        }
      ]
    },
    {
      "id": "core.sentence",
      "heading": "Sentence",
      "aliases": [
        "clause-level utterance"
      ],
      "category": "Core linguistics",
      "sourceFile": "terms/core-linguistics.md",
      "sourceAnchor": "sentence",
      "shortDefinition": "A complete unit of expression that can stand as a statement, question, command, or similar communicative act.",
      "explanation": "Sentences differ across languages. A sentence may omit elements that English would require, and sentence boundaries in writing may not match spoken phrasing exactly.",
      "relatedTerms": [
        {
          "label": "syntax",
          "target": "morphology-and-syntax.md#syntax"
        },
        {
          "label": "sentence pattern",
          "target": "morphology-and-syntax.md#sentence-pattern"
        }
      ]
    },
    {
      "id": "syntax.sentence-pattern",
      "heading": "Sentence Pattern",
      "aliases": [
        "construction"
      ],
      "category": "Morphology and syntax",
      "sourceFile": "terms/morphology-and-syntax.md",
      "sourceAnchor": "sentence-pattern",
      "shortDefinition": "A recurring sentence structure with a particular function.",
      "explanation": "Sentence patterns help learners understand how forms combine. A pattern may be productive, limited, or tied to a specific register.",
      "relatedTerms": [
        {
          "label": "grammatical structure",
          "target": "#grammatical-structure"
        },
        {
          "label": "syntax",
          "target": "#syntax"
        }
      ]
    },
    {
      "id": "korean.seven-final-consonant-sounds",
      "heading": "Seven Final Consonant Sounds",
      "aliases": [
        "seven 받침 sounds"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "seven-final-consonant-sounds",
      "shortDefinition": "The limited set of consonant sounds used for many Korean syllable-final pronunciations.",
      "explanation": "Many different written final consonants are pronounced as one of a smaller set of final consonant sounds when no following sound changes apply.",
      "relatedTerms": [
        {
          "label": "받침",
          "target": "#받침"
        },
        {
          "label": "sound change",
          "target": "phonetics-and-phonology.md#sound-change"
        }
      ]
    },
    {
      "id": "korean.simple-vowel",
      "heading": "Simple Vowel",
      "aliases": [
        "basic vowel"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "simple-vowel",
      "shortDefinition": "A vowel jamo taught as a basic written vowel form.",
      "explanation": "The term is useful pedagogically when distinguishing basic vowel jamo from y-vowels and w-vowels. It is a teaching category, not a claim that pronunciation is simple in every respect.",
      "relatedTerms": [
        {
          "label": "vowel jamo",
          "target": "#vowel-jamo"
        },
        {
          "label": "y-vowel",
          "target": "#y-vowel"
        },
        {
          "label": "w-vowel",
          "target": "#w-vowel"
        }
      ]
    },
    {
      "id": "phonology.sound-change",
      "heading": "Sound Change",
      "aliases": [
        "phonological process"
      ],
      "category": "Phonetics and phonology",
      "sourceFile": "terms/phonetics-and-phonology.md",
      "sourceAnchor": "sound-change",
      "shortDefinition": "A regular or context-sensitive change in pronunciation.",
      "explanation": "Sound change can describe historical changes or synchronic pronunciation rules inside a language. Curriculum notes should distinguish written form from actual pronunciation.",
      "relatedTerms": [
        {
          "label": "assimilation",
          "target": "#assimilation"
        },
        {
          "label": "palatalization",
          "target": "#palatalization"
        },
        {
          "label": "tensification",
          "target": "#tensification"
        }
      ]
    },
    {
      "id": "pragmatics.speech-level",
      "heading": "Speech Level",
      "aliases": [
        "style level"
      ],
      "category": "Semantics and pragmatics",
      "sourceFile": "terms/semantics-and-pragmatics.md",
      "sourceAnchor": "speech-level",
      "shortDefinition": "A grammatical or lexical level associated with politeness or formality.",
      "explanation": "Speech levels are especially important in Korean. They affect endings and social meaning, not just vocabulary.",
      "relatedTerms": [
        {
          "label": "politeness",
          "target": "#politeness"
        },
        {
          "label": "register",
          "target": "core-linguistics.md#register"
        },
        {
          "label": "ending",
          "target": "morphology-and-syntax.md#ending"
        }
      ]
    },
    {
      "id": "phonology.speech-sound",
      "heading": "Speech Sound",
      "aliases": [
        "phone"
      ],
      "category": "Phonetics and phonology",
      "sourceFile": "terms/phonetics-and-phonology.md",
      "sourceAnchor": "speech-sound",
      "shortDefinition": "A concrete sound produced in speech.",
      "explanation": "Speech sounds are physical events. A language may treat several similar speech sounds as versions of the same phoneme.",
      "relatedTerms": [
        {
          "label": "phoneme",
          "target": "#phoneme"
        },
        {
          "label": "allophone",
          "target": "#allophone"
        }
      ]
    },
    {
      "id": "writing.syllable",
      "heading": "Syllable",
      "aliases": [
        "syllabic unit"
      ],
      "category": "Writing systems",
      "sourceFile": "terms/writing-systems.md",
      "sourceAnchor": "syllable",
      "shortDefinition": "A rhythmic unit of speech built around a nucleus.",
      "explanation": "A syllable often contains an onset, nucleus, and coda, but languages differ in allowed syllable shapes. Syllable position is not the same as written block position.",
      "relatedTerms": [
        {
          "label": "onset",
          "target": "#onset"
        },
        {
          "label": "nucleus",
          "target": "#nucleus"
        },
        {
          "label": "coda",
          "target": "#coda"
        },
        {
          "label": "syllable block",
          "target": "#syllable-block"
        }
      ]
    },
    {
      "id": "korean.syllable-block",
      "heading": "Syllable Block",
      "aliases": [
        "Hangul syllable block"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "syllable-block",
      "shortDefinition": "A written Hangul block containing jamo arranged into a syllable-shaped unit.",
      "explanation": "A syllable block normally includes an initial position and a vowel position, and may include a final consonant position. Written block position should be distinguished from actual pronunciation.",
      "relatedTerms": [
        {
          "label": "syllable block",
          "target": "writing-systems.md#syllable-block"
        },
        {
          "label": "jamo",
          "target": "#jamo"
        },
        {
          "label": "받침",
          "target": "#받침"
        }
      ]
    },
    {
      "id": "writing.syllable-block",
      "heading": "Syllable Block",
      "aliases": [
        "block syllable"
      ],
      "category": "Writing systems",
      "sourceFile": "terms/writing-systems.md",
      "sourceAnchor": "syllable-block",
      "shortDefinition": "A written block that groups symbols into a syllable-shaped unit.",
      "explanation": "In Hangul, jamo are arranged into syllable blocks. A written block is a spelling unit and should not be confused with every detail of actual pronunciation.",
      "relatedTerms": [
        {
          "label": "syllable",
          "target": "#syllable"
        },
        {
          "label": "Hangul",
          "target": "korean.md#hangul"
        },
        {
          "label": "jamo",
          "target": "korean.md#jamo"
        }
      ]
    },
    {
      "id": "syntax.syntax",
      "heading": "Syntax",
      "aliases": [
        "sentence structure"
      ],
      "category": "Morphology and syntax",
      "sourceFile": "terms/morphology-and-syntax.md",
      "sourceAnchor": "syntax",
      "shortDefinition": "The study of how words and phrases combine into larger structures.",
      "explanation": "Syntax includes word order, sentence patterns, question formation, and relationships between parts of a sentence.",
      "relatedTerms": [
        {
          "label": "word order",
          "target": "#word-order"
        },
        {
          "label": "sentence pattern",
          "target": "#sentence-pattern"
        }
      ]
    },
    {
      "id": "korean.tense-consonant",
      "heading": "Tense Consonant",
      "aliases": [
        "Korean fortis consonant"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "tense-consonant",
      "shortDefinition": "A Korean consonant category with tense or reinforced articulation.",
      "explanation": "Korean tense consonants are often written with doubled consonant jamo, but \"tense consonant\" does not simply mean \"double consonant.\" The term refers to a phonological and phonetic contrast.",
      "relatedTerms": [
        {
          "label": "tense consonant",
          "target": "phonetics-and-phonology.md#tense-consonant"
        },
        {
          "label": "tensification",
          "target": "phonetics-and-phonology.md#tensification"
        }
      ]
    },
    {
      "id": "phonology.tense-consonant",
      "heading": "Tense Consonant",
      "aliases": [
        "fortis consonant"
      ],
      "category": "Phonetics and phonology",
      "sourceFile": "terms/phonetics-and-phonology.md",
      "sourceAnchor": "tense-consonant",
      "shortDefinition": "A consonant type produced with tense or reinforced articulation in some languages.",
      "explanation": "The term is especially relevant to Korean. A Korean tense consonant is not simply a \"double consonant\" in pronunciation, even though Hangul spelling uses doubled consonant letters for several tense consonants.",
      "relatedTerms": [
        {
          "label": "consonant",
          "target": "#consonant"
        },
        {
          "label": "tensification",
          "target": "#tensification"
        },
        {
          "label": "Korean tense consonant",
          "target": "korean.md#tense-consonant"
        }
      ]
    },
    {
      "id": "phonology.tensification",
      "heading": "Tensification",
      "aliases": [
        "fortition to tense consonant"
      ],
      "category": "Phonetics and phonology",
      "sourceFile": "terms/phonetics-and-phonology.md",
      "sourceAnchor": "tensification",
      "shortDefinition": "A process where a consonant becomes tense or reinforced.",
      "explanation": "Tensification is relevant to Korean sound patterns. It is a pronunciation process, not just a spelling convention.",
      "relatedTerms": [
        {
          "label": "tense consonant",
          "target": "#tense-consonant"
        },
        {
          "label": "sound change",
          "target": "#sound-change"
        }
      ]
    },
    {
      "id": "writing.transcription",
      "heading": "Transcription",
      "aliases": [
        "pronunciation representation"
      ],
      "category": "Writing systems",
      "sourceFile": "terms/writing-systems.md",
      "sourceAnchor": "transcription",
      "shortDefinition": "Writing down how something is pronounced.",
      "explanation": "Transcription represents sounds rather than original spelling. It should be distinguished from transliteration.",
      "relatedTerms": [
        {
          "label": "transliteration",
          "target": "#transliteration"
        },
        {
          "label": "phonetics",
          "target": "phonetics-and-phonology.md#phonetics"
        }
      ]
    },
    {
      "id": "writing.transliteration",
      "heading": "Transliteration",
      "aliases": [
        "script conversion"
      ],
      "category": "Writing systems",
      "sourceFile": "terms/writing-systems.md",
      "sourceAnchor": "transliteration",
      "shortDefinition": "Converting written symbols from one script to another.",
      "explanation": "Transliteration focuses on written form. It may not represent actual pronunciation accurately.",
      "relatedTerms": [
        {
          "label": "romanization",
          "target": "#romanization"
        },
        {
          "label": "transcription",
          "target": "#transcription"
        }
      ]
    },
    {
      "id": "core.vocabulary",
      "heading": "Vocabulary",
      "aliases": [
        "word stock"
      ],
      "category": "Core linguistics",
      "sourceFile": "terms/core-linguistics.md",
      "sourceAnchor": "vocabulary",
      "shortDefinition": "The words and fixed expressions known or used in a language or curriculum.",
      "explanation": "Vocabulary can include single words, compounds, formulaic phrases, and expressions that must be learned as units.",
      "relatedTerms": [
        {
          "label": "lexicon",
          "target": "#lexicon"
        },
        {
          "label": "word",
          "target": "#word"
        },
        {
          "label": "fixed expression",
          "target": "#fixed-expression"
        }
      ]
    },
    {
      "id": "phonology.vowel",
      "heading": "Vowel",
      "aliases": [
        "vowel sound"
      ],
      "category": "Phonetics and phonology",
      "sourceFile": "terms/phonetics-and-phonology.md",
      "sourceAnchor": "vowel",
      "shortDefinition": "A speech sound made with relatively open airflow that can form the center of a syllable.",
      "explanation": "Vowels are often syllable nuclei. Writing systems may represent vowels with letters, marks, combinations, or not represent them fully.",
      "relatedTerms": [
        {
          "label": "consonant",
          "target": "#consonant"
        },
        {
          "label": "semivowel",
          "target": "#semivowel"
        },
        {
          "label": "nucleus",
          "target": "writing-systems.md#nucleus"
        }
      ]
    },
    {
      "id": "korean.vowel-jamo",
      "heading": "Vowel Jamo",
      "aliases": [
        "vowel letter"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "vowel-jamo",
      "shortDefinition": "A Hangul jamo used to write a vowel element.",
      "explanation": "Vowel jamo represent written vowel elements. Some combine with glide-like elements in y-vowels and w-vowels.",
      "relatedTerms": [
        {
          "label": "jamo",
          "target": "#jamo"
        },
        {
          "label": "simple vowel",
          "target": "#simple-vowel"
        },
        {
          "label": "y-vowel",
          "target": "#y-vowel"
        },
        {
          "label": "w-vowel",
          "target": "#w-vowel"
        }
      ]
    },
    {
      "id": "korean.w-vowel",
      "heading": "W-Vowel",
      "aliases": [
        "w-glide vowel"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "w-vowel",
      "shortDefinition": "A Korean vowel spelling that contains a w-like glide before the main vowel.",
      "explanation": "W-vowels are often written with combined vowel jamo. Their romanized forms may not transparently show their structure.",
      "relatedTerms": [
        {
          "label": "semivowel",
          "target": "phonetics-and-phonology.md#semivowel"
        },
        {
          "label": "glide",
          "target": "phonetics-and-phonology.md#glide"
        },
        {
          "label": "vowel jamo",
          "target": "#vowel-jamo"
        }
      ]
    },
    {
      "id": "core.word",
      "heading": "Word",
      "aliases": [
        "lexical word"
      ],
      "category": "Core linguistics",
      "sourceFile": "terms/core-linguistics.md",
      "sourceAnchor": "word",
      "shortDefinition": "A meaningful language unit that speakers commonly treat as a unit.",
      "explanation": "The exact definition of a word differs by language and writing system. Some languages write spaces between words; others do not. Some grammatical elements behave like words in one respect and like affixes in another.",
      "relatedTerms": [
        {
          "label": "morpheme",
          "target": "#morpheme"
        },
        {
          "label": "lexicon",
          "target": "#lexicon"
        },
        {
          "label": "word order",
          "target": "morphology-and-syntax.md#word-order"
        }
      ]
    },
    {
      "id": "syntax.word-order",
      "heading": "Word Order",
      "aliases": [
        "constituent order"
      ],
      "category": "Morphology and syntax",
      "sourceFile": "terms/morphology-and-syntax.md",
      "sourceAnchor": "word-order",
      "shortDefinition": "The order in which words or phrases appear.",
      "explanation": "Word order can signal grammatical roles, emphasis, information structure, or sentence type. English order should not be treated as the universal model.",
      "relatedTerms": [
        {
          "label": "syntax",
          "target": "#syntax"
        },
        {
          "label": "sentence pattern",
          "target": "#sentence-pattern"
        }
      ]
    },
    {
      "id": "writing.writing-system",
      "heading": "Writing System",
      "aliases": [
        "writing tradition"
      ],
      "category": "Writing systems",
      "sourceFile": "terms/writing-systems.md",
      "sourceAnchor": "writing-system",
      "shortDefinition": "A conventional way of representing language visually.",
      "explanation": "A writing system includes scripts, spelling conventions, punctuation, and rules for how written symbols represent language. It is not the same thing as pronunciation.",
      "relatedTerms": [
        {
          "label": "script",
          "target": "#script"
        },
        {
          "label": "orthography",
          "target": "#orthography"
        }
      ]
    },
    {
      "id": "korean.y-vowel",
      "heading": "Y-Vowel",
      "aliases": [
        "iotized vowel"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "y-vowel",
      "shortDefinition": "A Korean vowel spelling that contains a y-like glide before the main vowel.",
      "explanation": "Y-vowels are relevant to Hangul reading because their written forms and pronunciation include a glide-like element.",
      "relatedTerms": [
        {
          "label": "semivowel",
          "target": "phonetics-and-phonology.md#semivowel"
        },
        {
          "label": "glide",
          "target": "phonetics-and-phonology.md#glide"
        },
        {
          "label": "vowel jamo",
          "target": "#vowel-jamo"
        }
      ]
    },
    {
      "id": "korean.batchim",
      "heading": "받침",
      "aliases": [
        "final consonant",
        "final consonant cluster"
      ],
      "category": "Korean terminology",
      "sourceFile": "terms/korean.md",
      "sourceAnchor": "받침",
      "shortDefinition": "The final consonant position in a Hangul syllable block.",
      "explanation": "받침 literally refers to the supporting final position in a Hangul syllable block. The term is commonly used for a final consonant or final consonant cluster written in that position. Written final consonants do not always preserve their ordinary initial pronunciation.",
      "relatedTerms": [
        {
          "label": "basic 받침",
          "target": "#basic-받침"
        },
        {
          "label": "compound 받침",
          "target": "#compound-받침"
        },
        {
          "label": "seven final consonant sounds",
          "target": "#seven-final-consonant-sounds"
        }
      ]
    }
  ]
};
