import { test, expect } from "@playwright/test";
import { captureDiagnostics, deepLink, login, resetUsers } from "./helpers.mjs";

test("reader remains keyboard-usable without destructive page overflow", async ({ page }) => {
  await resetUsers();
  const diagnostics = captureDiagnostics(page);
  await login(page, "A", deepLink());
  await expect(page.locator("#curriculum")).toBeVisible();
  await expect(page.locator("#source-locale")).toHaveCount(1);
  await page.locator("#menu-toggle").focus();
  await page.keyboard.press("Enter");
  await expect(page.locator("#menu-toggle")).toHaveAttribute("aria-expanded", "true");
  await expect(page.locator("#sidebar")).toHaveClass(/open/u);
  await expect(page.locator(".primary-nav button").first()).toBeDisabled();
  await page.keyboard.press("Escape");
  await expect(page.locator("#menu-toggle")).toBeFocused();
  await expect(page.locator("#menu-toggle")).toHaveAttribute("aria-expanded", "false");
  await page.locator("#chapters button", { hasText: "Chapter 10" }).focus();
  const focusStyle = await page.locator("#chapters button", { hasText: "Chapter 10" }).evaluate(node => getComputedStyle(node).outlineStyle);
  expect(focusStyle).not.toBe("none");
  await page.keyboard.press("Enter");
  await expect(page.locator("#reader")).toBeFocused();
  await expect(page.locator("#previous")).toBeVisible();
  await expect(page.locator("#next")).toBeVisible();
  await expect(page.locator("#chapter-content table")).toBeVisible();
  await expect(page.locator("#chapters")).toContainText("第十一章");
  const dimensions = await page.evaluate(() => ({ page: document.documentElement.scrollWidth, viewport: window.innerWidth }));
  expect(dimensions.page).toBeLessThanOrEqual(dimensions.viewport + 1);
  expect(diagnostics.issues, diagnostics.issues.join("\n")).toEqual([]);
});
